# Dockerfile.react
FROM node:17.9

# Set working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build:frontend

# Expose the port that Vite dev server listens on (assuming 3000, adjust if different)
EXPOSE 5173

# Command to run Vite dev server
CMD ["npm", "run", "dev-vite"]

