# Dockerfile.express
FROM node:17.9

# Set working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to leverage Docker cache
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build:backend

# Expose the port that the server listens on
EXPOSE 4000

# Command to run the server
CMD ["node", "./dist/server/server.js"]
